### ISSUE TITLE
编辑中出现的小问题

### ISSUE THREAD

**Issue by zhangxc097** [Qinbf/Deep-Learning-Tensorflow2#2]
5.5小节下的子小节编辑错误应是5.5.1，5.5.2等
https://user-images.githubusercontent.com/57701832/110230465-174b8780-7f4c-11eb-931f-cf2df1156ea8.png
17.1小节下的子小节编辑错误应是17.1.1，17.1.2等
https://user-images.githubusercontent.com/57701832/110230505-698ca880-7f4c-11eb-80d9-6118909bddfe.png
19.1小节下的子小节编辑错误应是19.1.1，19.1.2等
https://user-images.githubusercontent.com/57701832/110230522-83c68680-7f4c-11eb-879b-46244e91c498.png

**Comment by Qinbf** [comment]
@zhangxc097 谢谢，后面改正
